
## Crea la imagen apartir de un nginx de alpi
FROM nginx:alpine

## elimina todos los archivos por defecto que tiene la imagen
RUN rm -rf /usr/share/nginx/html/*

## copia el proyecto en la carpeta compartida
COPY . /usr/share/nginx/html

## exppon la imagen en el puerto 80
EXPOSE 80

## EJECUTAR EL LA TERMINAL EN LA CARPETA
## docker build -t mi-app:v1.0 .
## docker run -d -p 8080:80 mi-app:v1.0
